# -*- coding: utf-8 -*-
"""adaptive_emotion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kd1p_7MUt71rwLbAiv9u_V4LmAwfGO6F
"""

!pip install -q transformers torch accelerate

import torch
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM

# ==========================================
# 1. EMOTION DETECTION ENGINE (DistilBERT)
# ==========================================
# This model is specifically trained on 6 basic emotions:
# sadness, joy, love, anger, fear, surprise.
print("--- Loading Emotion Classifier ---")
emotion_classifier = pipeline(
    "text-classification",
    model="bhadresh-savani/distilbert-base-uncased-emotion",
    return_all_scores=False
)

# ==========================================
# 2. EMPATHETIC RESPONSE ENGINE (Blenderbot)
# ==========================================
# Blenderbot is the gold standard for conversational empathy.
print("--- Loading Empathetic Chat Model (Blenderbot) ---")
model_name = "facebook/blenderbot-400M-distill"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

def get_emotion_label(text):
    """Detects the underlying emotion of the input."""
    result = emotion_classifier(text)
    return result[0]['label']

def generate_emotion_aware_response(user_input):
    """Combines emotion detection with conversational generation."""

    # Step 1: Detect Emotion
    emotion = get_emotion_label(user_input)

    # Step 2: Inject Emotion into the Context
    # We guide the model by prefixing the context with the detected emotion
    context_input = f"The user feels {emotion}. User: {user_input}"

    # Step 3: Tokenize and Generate
    inputs = tokenizer(context_input, return_tensors="pt")

    # Using 'beam search' for higher quality, more coherent text
    res_tokens = model.generate(
        **inputs,
        max_length=60,
        num_beams=5,
        no_repeat_ngram_size=3,
        early_stopping=True
    )

    response = tokenizer.decode(res_tokens[0], skip_special_tokens=True)
    return emotion, response

# ==========================================
# 3. INTERACTIVE CHAT LOOP
# ==========================================
print("\n" + "="*40)
print("EMOTION-AWARE CHATBOT SYSTEM READY")
print("="*40)
print("(Type 'exit' to quit)\n")

while True:
    user_text = input("You: ")
    if user_text.lower() in ['exit', 'quit', 'bye']:
        print("Bot: Goodbye! Take care of yourself.")
        break

    try:
        detected_emo, bot_reply = generate_emotion_aware_response(user_text)

        # Displaying the 'Internal Logic' for the Research Paper
        print(f"  [LOG] Detected Emotion: {detected_emo.upper()}")
        print(f"Bot: {bot_reply}\n")
    except Exception as e:
        print(f"Error: {e}")

from sklearn.metrics import accuracy_score, classification_report

# Sample test data (you can expand this)
texts = [
    "I am very happy today",
    "I feel so sad and depressed",
    "I am angry about the results",
    "This is surprising!",
    "I am scared of exams"
]

true_labels = ["joy", "sadness", "anger", "surprise", "fear"]

predicted = [get_emotion_label(t) for t in texts]

print("Accuracy:", accuracy_score(true_labels, predicted))
print(classification_report(true_labels, predicted))

from sklearn.metrics import accuracy_score, classification_report

# Expanded test dataset (30 samples)
texts = [
    # Joy
    "I am very happy today",
    "This is the best day of my life",
    "I got selected for the job!",
    "I feel amazing and excited",
    "I am really enjoying this moment",

    # Sadness
    "I feel so sad and depressed",
    "I lost my best friend",
    "I am feeling very low today",
    "Nothing is going right in my life",
    "I feel like crying",

    # Anger
    "I am angry about the results",
    "This makes me so frustrated",
    "I hate this situation",
    "Why is everything so annoying",
    "I am really mad right now",

    # Fear
    "I am scared of exams",
    "I feel nervous about tomorrow",
    "This situation is frightening",
    "I am worried about my future",
    "I feel anxious and afraid",

    # Surprise
    "This is surprising!",
    "I didn't expect this at all",
    "Wow this is shocking",
    "That was totally unexpected",
    "I am amazed by the result",

    # Love
    "I love my family so much",
    "I really like this person",
    "I feel so attached to you",
    "You mean a lot to me",
    "I adore this moment"
]

true_labels = [
    # Joy
    "joy", "joy", "joy", "joy", "joy",

    # Sadness
    "sadness", "sadness", "sadness", "sadness", "sadness",

    # Anger
    "anger", "anger", "anger", "anger", "anger",

    # Fear
    "fear", "fear", "fear", "fear", "fear",

    # Surprise
    "surprise", "surprise", "surprise", "surprise", "surprise",

    # Love
    "love", "love", "love", "love", "love"
]

# Predictions
predicted = [get_emotion_label(t) for t in texts]

# Evaluation
print("Accuracy:", accuracy_score(true_labels, predicted))
print("\nClassification Report:\n")
print(classification_report(true_labels, predicted))

def generate_emotion_aware_response(user_input):
    emotion = get_emotion_label(user_input)

    # Stronger emotional conditioning
    context_input = f"User is feeling {emotion}. Respond empathetically. User: {user_input}"

    inputs = tokenizer(context_input, return_tensors="pt")

    res_tokens = model.generate(
        **inputs,
        max_length=60,
        num_beams=7,  # increased beams
        no_repeat_ngram_size=3,
        early_stopping=True
    )

    response = tokenizer.decode(res_tokens[0], skip_special_tokens=True)
    return emotion, response

def normalize_label(label):
    mapping = {
        "happy": "joy",
        "afraid": "fear",
        "surprised": "surprise"
    }
    return mapping.get(label, label)

predicted = [normalize_label(get_emotion_label(t)) for t in texts]

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

labels = ["joy","sadness","anger","fear","surprise","love"]
cm = confusion_matrix(true_labels, predicted, labels=labels)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(range(len(labels)), labels)
plt.yticks(range(len(labels)), labels)

for i in range(len(labels)):
    for j in range(len(labels)):
        plt.text(j, i, cm[i, j], ha='center')

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(true_labels, predicted, labels=["joy","sadness","anger","fear","surprise","love"])

sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=["joy","sadness","anger","fear","surprise","love"],
            yticklabels=["joy","sadness","anger","fear","surprise","love"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()